/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package brentwoodmon;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author zhanglianghui
 */
public class PlayerCustomization extends javax.swing.JPanel {

    /**
     * Creates new form PlayerCustomization
     */
    private Image snorlax;
    private Image shaq;
    private Image hero;
    private Image bull;
    private final PlayerCustomizationIntf responseHandler;
    private Image myImage;
    private String type;

    public PlayerCustomization(Image snorlax, Image shaq, Image hero,Image bull, PlayerCustomizationIntf responseHandler) {
        initComponents();

        this.snorlax = snorlax;
        this.shaq = shaq;
        this.hero = hero;
        this.bull = bull;
        
        this.responseHandler = responseHandler;
        this.myImage = snorlax;
    }

    public void close() {
        this.getParent().setVisible(false);
        ((JFrame) this.getTopLevelAncestor()).dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnShaq = new javax.swing.JButton();
        jbtnSnorlax = new javax.swing.JButton();
        jlblInstructionOne = new javax.swing.JLabel();
        jbtnHero = new javax.swing.JButton();
        jbtnBull = new javax.swing.JButton();
        jlblInstructionTwo = new javax.swing.JLabel();
        jtxtCustomizedName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jlblMyImage = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jbtnConfirm = new javax.swing.JToggleButton();

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jbtnShaq.setFont(new java.awt.Font("华文隶书", 0, 24)); // NOI18N
        jbtnShaq.setText("Shaq");
        jbtnShaq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnShaqMouseClicked(evt);
            }
        });

        jbtnSnorlax.setFont(new java.awt.Font("华文隶书", 0, 24)); // NOI18N
        jbtnSnorlax.setText("Snorlax");
        jbtnSnorlax.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnSnorlaxMouseClicked(evt);
            }
        });

        jlblInstructionOne.setFont(new java.awt.Font("华文隶书", 0, 24)); // NOI18N
        jlblInstructionOne.setText("Please Select A Character:");

        jbtnHero.setFont(new java.awt.Font("华文隶书", 0, 24)); // NOI18N
        jbtnHero.setText("Hero");
        jbtnHero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnHeroMouseClicked(evt);
            }
        });

        jbtnBull.setFont(new java.awt.Font("华文隶书", 0, 24)); // NOI18N
        jbtnBull.setText("Bull");
        jbtnBull.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnBullMouseClicked(evt);
            }
        });

        jlblInstructionTwo.setFont(new java.awt.Font("华文隶书", 0, 24)); // NOI18N
        jlblInstructionTwo.setText("Please Enter Your Name:");

        jtxtCustomizedName.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblInstructionOne, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jbtnBull, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnHero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnShaq, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtnSnorlax, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                            .addComponent(jlblInstructionTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtCustomizedName, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jlblInstructionOne, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnSnorlax, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnShaq, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnHero, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnBull, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlblInstructionTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtCustomizedName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));

        jlblMyImage.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblMyImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblMyImage, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        jbtnConfirm.setFont(new java.awt.Font("华文隶书", 0, 24)); // NOI18N
        jbtnConfirm.setText("Confirm");
        jbtnConfirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnConfirmMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnConfirm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSnorlaxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnSnorlaxMouseClicked
        jlblMyImage.setIcon(new ImageIcon(snorlax.getScaledInstance(250, 250, Image.SCALE_SMOOTH)));
        this.myImage = snorlax;
        this.type = CharacterType.SNORLAX;
    }//GEN-LAST:event_jbtnSnorlaxMouseClicked

    private void jbtnShaqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnShaqMouseClicked
        jlblMyImage.setIcon(new ImageIcon(shaq.getScaledInstance(200, 250, Image.SCALE_SMOOTH)));
        this.myImage = shaq;
        this.type = CharacterType.SHAQ;
    }//GEN-LAST:event_jbtnShaqMouseClicked

    private void jbtnHeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnHeroMouseClicked
        jlblMyImage.setIcon(new ImageIcon(hero.getScaledInstance(200, 250, Image.SCALE_SMOOTH)));
        this.myImage = hero;
        this.type = CharacterType.HERO;
    }//GEN-LAST:event_jbtnHeroMouseClicked

    private void jbtnConfirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnConfirmMouseClicked
        if (responseHandler != null) {
            responseHandler.handlePlayerCustomizationResponse(this.jtxtCustomizedName.getText(), myImage, this.type);
            close();
        }
    }//GEN-LAST:event_jbtnConfirmMouseClicked

    private void jbtnBullMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnBullMouseClicked
        jlblMyImage.setIcon(new ImageIcon(bull.getScaledInstance(250, 250, Image.SCALE_SMOOTH)));
        this.myImage = bull;
        this.type = CharacterType.BULL;
    }//GEN-LAST:event_jbtnBullMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jbtnBull;
    private javax.swing.JToggleButton jbtnConfirm;
    private javax.swing.JButton jbtnHero;
    private javax.swing.JButton jbtnShaq;
    private javax.swing.JButton jbtnSnorlax;
    private javax.swing.JLabel jlblInstructionOne;
    private javax.swing.JLabel jlblInstructionTwo;
    private javax.swing.JLabel jlblMyImage;
    private javax.swing.JTextField jtxtCustomizedName;
    // End of variables declaration//GEN-END:variables
}
